"use client";

import React, { useEffect, useState } from 'react';
import { StoreService } from '@/services/storeService';
import { Producto } from '@/types';
import { useAuth } from '@/context/AuthContext';
import { useRouter } from 'next/navigation';
import { Plus, Edit, Trash2, X, Save } from 'lucide-react';

export default function AdminProductsPage() {
    const { user, loading: authLoading } = useAuth();
    const router = useRouter();
    const [products, setProducts] = useState<Producto[]>([]);
    const [loading, setLoading] = useState(true);

    // Edit/Create State
    const [isEditing, setIsEditing] = useState(false);
    const [editingId, setEditingId] = useState<string | null>(null);
    const [formData, setFormData] = useState<Partial<Producto>>({});

    useEffect(() => {
        if (!authLoading) {
            if (!user || user.rol !== 'admin') {
                router.push('/');
                return;
            }
            fetchProducts();
        }
    }, [user, authLoading, router]);

    const fetchProducts = async () => {
        const data = await StoreService.getProductos();
        setProducts([...data]); // Copy to force refresh
        setLoading(false);
    };

    const handleEdit = (product: Producto) => {
        setEditingId(product.id);
        setFormData({ ...product });
        setIsEditing(true);
    };

    const handleCreate = () => {
        setEditingId(null);
        setFormData({
            nombre: '',
            tipo: 'gotero',
            categoria: '',
            descripcion: '',
            stockDisponible: 0,
            activo: true
        });
        setIsEditing(true);
    };

    const handleDelete = async (id: string) => {
        if (confirm('¿Estás seguro de eliminar este producto?')) {
            await StoreService.deleteProduct(id);
            fetchProducts();
        }
    };

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        try {
            if (editingId) {
                // Update
                await StoreService.updateProduct(editingId, formData);
            } else {
                // Create
                // @ts-ignore - ID is generated by backend
                await StoreService.addProduct(formData as Producto);
            }
            setIsEditing(false);
            fetchProducts();
        } catch (error) {
            console.error(error);
            alert('Error al guardar');
        }
    };

    if (loading || authLoading) return <p>Cargando...</p>;

    if (isEditing) {
        return (
            <div style={{ maxWidth: '600px', margin: '0 auto' }}>
                <h2 style={{ marginBottom: '1.5rem' }}>{editingId ? 'Editar Producto' : 'Nuevo Producto'}</h2>
                <form onSubmit={handleSave} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                    <div>
                        <label style={{ display: 'block', marginBottom: '0.5rem' }}>Nombre</label>
                        <input
                            type="text"
                            value={formData.nombre || ''}
                            onChange={e => setFormData({ ...formData, nombre: e.target.value })}
                            required
                            style={{ width: '100%', padding: '0.75rem', borderRadius: 'var(--radius)', border: '1px solid hsl(var(--input))' }}
                        />
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                        <div>
                            <label style={{ display: 'block', marginBottom: '0.5rem' }}>Tipo</label>
                            <select
                                value={formData.tipo || 'gotero'}
                                onChange={e => setFormData({ ...formData, tipo: e.target.value as any })}
                                style={{ width: '100%', padding: '0.75rem', borderRadius: 'var(--radius)', border: '1px solid hsl(var(--input))' }}
                            >
                                <option value="gotero">Gotero</option>
                                <option value="flor">Flor</option>
                                <option value="crema">Crema</option>
                                <option value="otro">Otro</option>
                            </select>
                        </div>
                        <div>
                            <label style={{ display: 'block', marginBottom: '0.5rem' }}>Categoría / Químico</label>
                            <input
                                type="text"
                                value={formData.categoria || ''}
                                onChange={e => setFormData({ ...formData, categoria: e.target.value })}
                                required
                                style={{ width: '100%', padding: '0.75rem', borderRadius: 'var(--radius)', border: '1px solid hsl(var(--input))' }}
                            />
                        </div>
                    </div>

                    <div>
                        <label style={{ display: 'block', marginBottom: '0.5rem' }}>Descripción</label>
                        <textarea
                            value={formData.descripcion || ''}
                            onChange={e => setFormData({ ...formData, descripcion: e.target.value })}
                            rows={3}
                            style={{ width: '100%', padding: '0.75rem', borderRadius: 'var(--radius)', border: '1px solid hsl(var(--input))' }}
                        />
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                        <div>
                            <label style={{ display: 'block', marginBottom: '0.5rem' }}>Stock</label>
                            <input
                                type="number"
                                value={formData.stockDisponible ?? 0}
                                onChange={e => setFormData({ ...formData, stockDisponible: parseInt(e.target.value) })}
                                required
                                style={{ width: '100%', padding: '0.75rem', borderRadius: 'var(--radius)', border: '1px solid hsl(var(--input))' }}
                            />
                        </div>
                        <div style={{ display: 'flex', alignItems: 'center' }}>
                            <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer' }}>
                                <input
                                    type="checkbox"
                                    checked={formData.activo ?? true}
                                    onChange={e => setFormData({ ...formData, activo: e.target.checked })}
                                    style={{ transform: 'scale(1.2)' }}
                                />
                                Activo / Disponible
                            </label>
                        </div>
                    </div>

                    <div style={{ display: 'flex', gap: '1rem', marginTop: '1rem' }}>
                        <button
                            type="submit"
                            style={{
                                flex: 1,
                                padding: '1rem',
                                backgroundColor: 'hsl(var(--primary))',
                                color: 'hsl(var(--primary-foreground))',
                                border: 'none',
                                borderRadius: 'var(--radius)',
                                fontWeight: 600,
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                gap: '0.5rem'
                            }}
                        >
                            <Save size={18} /> Guardar
                        </button>
                        <button
                            type="button"
                            onClick={() => setIsEditing(false)}
                            style={{
                                flex: 1,
                                padding: '1rem',
                                backgroundColor: 'transparent',
                                border: '1px solid hsl(var(--border))',
                                borderRadius: 'var(--radius)',
                                fontWeight: 600,
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                gap: '0.5rem'
                            }}
                        >
                            <X size={18} /> Cancelar
                        </button>
                    </div>
                </form>
            </div>
        );
    }

    return (
        <div>
            <div style={{ marginBottom: '2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                    <h1 style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>Gestión de Productos</h1>
                    <p style={{ color: 'hsl(var(--muted-foreground))' }}>Alta, baja y modificación de stock.</p>
                </div>
                <button
                    onClick={handleCreate}
                    style={{
                        padding: '0.75rem 1.25rem',
                        backgroundColor: 'hsl(var(--primary))',
                        color: 'hsl(var(--primary-foreground))',
                        border: 'none',
                        borderRadius: 'var(--radius)',
                        fontWeight: 600,
                        display: 'flex',
                        alignItems: 'center',
                        gap: '0.5rem'
                    }}
                >
                    <Plus size={18} /> Nuevo Producto
                </button>
            </div>

            <div style={{ overflowX: 'auto' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: '800px' }}>
                    <thead>
                        <tr style={{ borderBottom: '1px solid hsl(var(--border))', textAlign: 'left' }}>
                            <th style={{ padding: '1rem' }}>Nombre</th>
                            <th style={{ padding: '1rem' }}>Tipo</th>
                            <th style={{ padding: '1rem' }}>Cat.</th>
                            <th style={{ padding: '1rem' }}>Stock</th>
                            <th style={{ padding: '1rem' }}>Estado</th>
                            <th style={{ padding: '1rem', textAlign: 'right' }}>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {products.map(p => (
                            <tr key={p.id} style={{ borderBottom: '1px solid hsl(var(--border))' }}>
                                <td style={{ padding: '1rem' }}>{p.nombre}</td>
                                <td style={{ padding: '1rem', textTransform: 'capitalize' }}>{p.tipo}</td>
                                <td style={{ padding: '1rem' }}>{p.categoria}</td>
                                <td style={{ padding: '1rem', fontWeight: 600 }}>{p.stockDisponible}</td>
                                <td style={{ padding: '1rem' }}>
                                    {p.activo ? (
                                        <span style={{ color: 'hsl(var(--primary))' }}>Activo</span>
                                    ) : (
                                        <span style={{ color: 'hsl(var(--muted-foreground))' }}>Inactivo</span>
                                    )}
                                </td>
                                <td style={{ padding: '1rem', textAlign: 'right' }}>
                                    <button
                                        onClick={() => handleEdit(p)}
                                        style={{
                                            border: 'none',
                                            background: 'none',
                                            color: 'hsl(var(--foreground))',
                                            padding: '0.5rem',
                                            cursor: 'pointer'
                                        }}
                                    >
                                        <Edit size={18} />
                                    </button>
                                    <button
                                        onClick={() => handleDelete(p.id)}
                                        style={{
                                            border: 'none',
                                            background: 'none',
                                            color: 'hsl(var(--destructive))',
                                            padding: '0.5rem',
                                            cursor: 'pointer'
                                        }}
                                    >
                                        <Trash2 size={18} />
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
